import { jobHelp } from "./job/job.js"

export function help(): string {
  return [
    "aq  Aquin CLI",
    "",
    "A train is a directory.",
    "",
    "  aq                      agent chat (TTY)",
    "  aq agent                same",
    "  aq chat list            previous chats",
    "  aq chat last            resume the latest",
    "  aq chat <id>           resume that chat",
    "  aq ask [dir] <prompt>   one-shot answer (no chat UI)",
    "  aq ask --json [dir] <prompt>",
    "  aq help                 this text",
    "  aq version              framework version (-v / --version; version --verbose for paths)",
    "  aq login                open aq.aquin.app/?view=desktop&client=cli, then paste the code",
    "  aq login --token <aq-…>  paste an existing CLI token",
    "  aq login --check        who is signed in",
    "  aq logout [email]       drop the active (or that) account",
    "  aq switch [email]       list or switch ~/.aquin accounts",
    "  aq provider             list openai / anthropic / grok / ollama",
    "  aq provider <name>      save key (hidden) and use it",
    "  aq provider use <name>  switch",
    "  aq init                 new train folder aq-experiment (or -new1, -new2, …)",
    "  aq init <name>          same, named folder (also -newN if taken)",
    "  aq fork <new-dir>      copy this train; skip jobs/ and artifacts/",
    "  aq fork <src> <dest>   copy that train to dest",
    "                          --lo --hi --why \"...\"  predicted range (agent required)",
    "                          --novelty method|data|architecture|hyperparam",
    "  aq forecast [dir]      show predicted vs actual, calibration, budget",
    "  aq forecast --lo n --hi n --why \"...\"   write forecast.yaml (before train/fork)",
    "  aq learn [dir]         ack memory/heuristics.md (every 10 forecast-forks)",
    "  aq checkout <id>        restore that run's tree into cwd",
    "  aq checkout <id> <dest>  tree + that job in a new dir",
    "  aq data hash [dir] [--snapshot]  hash recipe data.path",
    "  aq train [dir]          fit; write checkpoints + artifacts/metrics.jsonl",
    "                          recipe guard.safety / guard.leak = opt-in fail-closed watches",
    "  aq eval [dir] [name] [--ckpt name]  score evals/<name> (all evals/ if omitted)",
    "  aq checkpoint [dir] [--keep name]  list or copy last to name",
    "  aq serve [dir] [prompt] [--ckpt name] [--max-tokens n] [--temperature t]",
    "  aq tool [dir] [name] [-- args]  run tools/<name>; no name lists",
    "  aq schedule [dir] | tick | run <name>  sweeps/cron/resume-on-fail",
    "  aq stage [dir] | init <name> | <name> | eval <name>  nested trains",
    "  aq diff [dir] [<a> <b>]     compare run records (files, not screenshots)",
    "  aq status [dir]            jobs, last run, eval, schedule logs",
    "  aq doctor [dir]           health check (cli, provider, train, skills, mcp)",
    "  aq spawn run [dir] -- <prompt>  start a worker agent (job)",
    "  aq spawn run --kill -- <prompt>  critic: cheapest disproof",
    "  aq spawn list [dir]       worker agents",
    "  aq spawn log [dir] <id>  that agent's log",
    "  aq spawn cancel [dir] <id>",
    jobHelp(),
    "",
    "init writes:",
    "  instructions.md  recipe.yaml  train.ts",
    "  data/ skills/ memory/ tools/ sandbox/ jobs/ evals/",
    "  artifacts/ connections/ schedules/ stages/ methods/",
    "",
    "Kernel (Python): aq writes artifacts/request.json, reads artifacts/result.json.",
  ].join("\n")
}
