name = "aqfw-releases"
main = "src/index.ts"
compatibility_date = "2024-08-01"

[[r2_buckets]]
binding = "RELEASES"
bucket_name = "aqfw-releases"

[[routes]]
pattern = "aq.aquin.app/releases/*"
zone_name = "aquin.app"

[[routes]]
pattern = "aq.aquin.app/framework/install.sh"
zone_name = "aquin.app"
